"""Compatibility entry point for the governed-effect runtime seed.

The runtime is split into focused modules; this module re-exports the public v0
surface and keeps the local adapter self-test CLI stable.
"""

from __future__ import annotations

from fermata.file_adapter import (
    FileWriteAdapter,
    evaluate_file_write,
    nofollow_directory_flags,
    nofollow_file_flags,
    open_file_parent_fd,
    sample_proposal,
    sample_scope,
    target_rejection_for_existing_path,
)
from fermata.interpreter import interpret
from fermata.memory_adapter import (
    MEMORY_LIFESPANS,
    MEMORY_RECORD_STRING_FIELDS,
    MemoryWriteAdapter,
    evaluate_memory_write,
    memory_store_path,
    sample_memory_proposal,
    sample_memory_scope,
    validate_memory_record,
)
from fermata.policy_parser import (
    PolicyParseError,
    parse_agent_proposal_json,
    parse_policy_block,
)
from fermata.runtime_core import (
    append_trace_ledger,
    approved_result,
    ensure_private_directory,
    evaluate_with_adapter,
    is_inside,
    normalize_target,
    pause,
    reject,
    trace_ledger_path,
)
from fermata.runtime_ir import (
    SCHEMA_VERSION,
    AdapterPreparation,
    ApprovalAuthority,
    ApprovalDecision,
    ApprovalStatus,
    CommitEvidence,
    EffectResult,
    EffectState,
    GovernedAdapter,
    Intent,
    Proposal,
    RejectionReason,
    Scope,
    SpeechAct,
    Trace,
    approval_for,
    approval_rejection_reason,
    canonical_json_bytes,
    enum_value,
    intent_sha256,
    make_approval_decision,
    now_timestamp,
    parse_iso_timestamp,
    sha256_bytes,
    to_jsonable,
)
from fermata.self_tests import main, run_self_tests


__all__ = [
    "SCHEMA_VERSION",
    "AdapterPreparation",
    "ApprovalAuthority",
    "ApprovalDecision",
    "ApprovalStatus",
    "CommitEvidence",
    "EffectResult",
    "EffectState",
    "FileWriteAdapter",
    "GovernedAdapter",
    "Intent",
    "MEMORY_LIFESPANS",
    "MEMORY_RECORD_STRING_FIELDS",
    "MemoryWriteAdapter",
    "PolicyParseError",
    "Proposal",
    "RejectionReason",
    "Scope",
    "SpeechAct",
    "Trace",
    "append_trace_ledger",
    "approval_for",
    "approval_rejection_reason",
    "approved_result",
    "canonical_json_bytes",
    "enum_value",
    "ensure_private_directory",
    "evaluate_file_write",
    "evaluate_memory_write",
    "evaluate_with_adapter",
    "intent_sha256",
    "interpret",
    "is_inside",
    "main",
    "make_approval_decision",
    "memory_store_path",
    "nofollow_directory_flags",
    "nofollow_file_flags",
    "normalize_target",
    "now_timestamp",
    "open_file_parent_fd",
    "parse_agent_proposal_json",
    "parse_iso_timestamp",
    "parse_policy_block",
    "pause",
    "reject",
    "run_self_tests",
    "sample_memory_proposal",
    "sample_memory_scope",
    "sample_proposal",
    "sample_scope",
    "sha256_bytes",
    "target_rejection_for_existing_path",
    "to_jsonable",
    "trace_ledger_path",
    "validate_memory_record",
]
